name: Run Danger on PR

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd bots && yarn install
      - name: Danger
        run: cd bots && yarn danger ci --use-github-checks --failOnErrors --id danger_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
